### PR TITLE
Feed stock patches

### PR DESCRIPTION
**Pull request by raimis**
This PR contributes the patches (https://github.com/conda-forge/openmm-atmmetaforce-plugin-feedstock/tree/main/recipe) introduced by:
- https://github.com/conda-forge/openmm-atmmetaforce-plugin-feedstock/pull/5
- https://github.com/conda-forge/openmm-atmmetaforce-plugin-feedstock/pull/6

After merging this PR:
- An new version has to be tagged
- The patches removed from the feedstock
- New packages rebuilt

### CODE REVIEW

**Comment by raimis** [comment]
@egallicc could you review?

**Comment by egallicc** [comment]
Thank you. So after merging this PR I should create a new release? And the conda-forge feedstock should point to the new release?

**Comment by egallicc** [comment]
Also, the plugin currently supports both OpenMM 7.7 and 8.0. There is no requirement that this PR be compatible with OpenMM 7.7, but I would like to know if this PR breaks backward compatibility for documentation purposes.

**Comment by raimis** [comment]
> Also, the plugin currently supports both OpenMM 7.7 and 8.0. There is no requirement that this PR be compatible with OpenMM 7.7, but I would like to know if this PR breaks backward compatibility for documentation purposes.

In https://github.com/conda-forge/openmm-atmmetaforce-plugin-feedstock/pull/6, first I applied these patches and only after I upgraded to OpenMM 8. So, the backward compatibility is not broken.

**Comment by raimis** [comment]
> Thank you. So after merging this PR I should create a new release? And the conda-forge feedstock should point to the new release?

Yes, the new release is needed. After https://github.com/conda-forge/openmm-atmmetaforce-plugin-feedstock/pull/6, I'll make a new PR to build packages for the new release.

**Comment by egallicc** [comment]
Great. Thanks! Creating the release now ...

**Comment by egallicc** [comment]
Done: https://github.com/Gallicchio-Lab/openmm-atmmetaforce-plugin/releases/tag/v0.3.4

**Pull request merged**
